apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-server-streaming
  template:
    metadata:
      labels:
        app: grpc-server-streaming
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: grpc-server-streaming
        image: ghcr.io/ivankovnatsky/images-public/grpc-server-streaming:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-server-streaming
spec:
  selector:
    app: grpc-server-streaming
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
