apiVersion: batch/v1
kind: Job
metadata:
  name: grpc-client-streaming-job
spec:
  template:
    metadata:
      labels:
        app: grpc-client-streaming
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: grpc-client-streaming
        image: ghcr.io/ivankovnatsky/images-public/grpc-client-streaming:latest
        command: ["/client"]
        args:
          - "-duration=5"
          - "-insecure=true"
          - "-server=grpc-server-streaming.default.svc.cluster.local:8080"
      restartPolicy: Never
